name: Assign to someone
on:
  issues:
    types: [opened, labeled]
jobs:
  applyTriageLabel:
    name: Apply Triage Label
    runs-on: ubuntu-latest
    # if: github.repository == 'microsoft/vscode-python' && github.event.labels.length == 0
    if: github.event.labels.length == 0
    steps:
      - uses: actions/checkout@v2
      - name: Day of week
        id: day
        run: |
          echo ::set-output name=number::$(node -p -e "new Date().getDay()")
        shell: bash
      - name: Week Number
        id: week
        run: |
          echo ::set-output name=number::$(node .github/workflows/week.js)
        shell: bash
      - name: Print day and week
        run: |
          echo ${{steps.day.outputs.number}}
          echo ${{steps.week.outputs.number}}
        shell: bash
      - name: Assign to @David (sat, sun, mon - odd week)
        if: steps.day.outputs.number == 6 || steps.day.outputs.number == 0 || steps.day.outputs.number == 1
        uses: actions/github@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: assign @DonJayamanne
      - name: Assign to @Joyce (sat, sun, mon - even week)
        if: steps.day.outputs.number == 6 || steps.day.outputs.number == 0 || steps.day.outputs.number == 1
        uses: actions/github@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: assign @DonJayamanne
      - name: Assign to @Rich (tues)
        if: steps.day.outputs.number == 2
        uses: actions/github@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: assign @DonJayamanne
      - name: Assign to @Ian (wed)
        if: steps.day.outputs.number == 3
        uses: actions/github@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: assign @DonJayamanne
      - name: Assign to @DonJayamanne
        if: steps.day.outputs.number == 4
        uses: actions/github@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: assign @DonJayamanne
      - name: Assign to @Claudia (fri)
        if: steps.day.outputs.number == 5
        uses: actions/github@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: assign @DonJayamanne
